### ISSUE TITLE
error: no download tool found, please install curl, wget or busybox wget (when I change the DockerFile and restart the workspace). What needs to be changed further?

### ISSUE THREAD

**Issue by johnstcn** [coder/terraform-provider-envbuilder#42]
@johnstcn I still get  error: no download tool found, please install curl, wget or busybox wget (when I change the DockerFile and restart the workspace). What needs to be changed further?

[terraform.txt](https://github.com/user-attachments/files/16829946/terraform.txt)

_Originally posted by @datapedd in https://github.com/coder/terraform-provider-envbuilder/issues/31#issuecomment-2323434755_

**Comment by johnstcn** [comment]
@datapedd that mesesage is returned by the [agent provision script](https://github.com/coder/coder/blob/main/provisionersdk/scripts/bootstrap_linux.sh#L32). Can you share the `devcontainer.json` or `Dockerfile` that you're trying to build? You may need to add a command to install `curl` or `wget`.

**Comment by datapedd** [comment]
Curl is in the Dockerfile. The first time it builds fine, but when I just restart it, then it fails.

**Comment by datapedd** [comment]
Found the problem. It is that curl has to be all the time in the dockerfile, if removed and then the workspace is restarted, then if fails. Should also be changed in the readme as it is not in it. 

![image](https://github.com/user-attachments/assets/43de2347-e962-4e05-8ce8-180a53fc2202)

**Comment by johnstcn** [comment]
> Should also be changed in the readme as it is not in it.

Thanks for the update @datapedd ! It sounds like a section specifically related to integrating with Coder would be useful here.
